### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by JonnyBro**
Update Russian translation from poorly Google translated one to my own. I'll open it for review after testing it myself.

### CODE REVIEW

**Comment by sunwinbus** [comment]
Thank you. I will review it in a few days.

Due to the size of checkboxes and buttons, some of the translation might be further shortened.

**Comment by JonnyBro** [comment]
Thanks! Let me know if any strings need to be shortened.

**Comment by sunwinbus** [comment]
PixPin_2024-08-16_19-25-45
```
  select: 'Профили и Сохранения',
  mileage: 'Приблизительная дистанция',
```
Could you please help simplify these 2 translation?

**Comment by JonnyBro** [comment]
Sure! Let's try those.

**Comment by sunwinbus** [comment]
PixPin_2024-08-16_22-46-54
```
  select: 'Профили и Сохранения',
```
This translation is still a little bit long. Would `Профили` be ok?
If it is in English, compared to `Profiles & Saves`, `Profiles` is also ok for me.

**Comment by JonnyBro** [comment]
I think `Профили (Profiles)` is fine, can't think of good and short wors for this button. I'll make another pull request if I think of something.

**Comment by sunwinbus** [comment]
Thank you very much for your translation.
Pull requests for translation purpose will not be merged, but I will update the credit and translation. Furthermore, the release date of the new version is still unsure. Probably it will come after ETS2/ATS 1.51.

**Pull request closed without merging**
